UpperToolsProject/Models/Atividade.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace UpperToolsProject.Models
{
   [Table("Atividade")]
    public class Atividade
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Display(Name ="Descrição")]
        [JsonProperty("text")]
        public string Text { get; set; }
        [Display(Name ="Código CNAE")]
        [JsonProperty("code")]
        public string Code { get; set; }
        [ForeignKey("EmpresaCnpj")]
        public string EmpresaCnpj { get; set; }
    }

}

UpperToolsProject/Models/AtividadeS.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace UpperToolsProject.Models
{
   [Table("AtividadeS")]
    public class AtividadeS
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Display(Name = "Descrição")]
        [JsonProperty("text")]
        public string Text { get; set; }
        [Display(Name = "Código CNAE")]
        [JsonProperty("code")]
        public string Code { get; set; }
        [ForeignKey("EmpresaCnpj")]
        public string EmpresaCnpj { get; set; }
    }

}

UpperToolsProject/Models/Empresa.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace UpperToolsProject.Models
{
    [Table("Empresa")]
    public class Empresa
    {
        [Key]
        [Display(Name = "CNPJ")]
        [Required(ErrorMessage = "Preencha este campo.")]
        [RegularExpression("[0-9]{2}\\.?[0-9]{3}\\.?[0-9]{3}\\/?[0-9]{4}\\-?[0-9]{2}", ErrorMessage = "Digite um CNPJ válido")]
        public string Cnpj { get; set; }

        [StringLength(100)]
        [Display(Name ="Nome")]
        [Required(ErrorMessage ="Preencha este campo")]
        public string Nome { get; set; }

        [Display(Name = "Data da situacção")]
        [StringLength(20)]
        public string DataSituacao { get; set; }

        [Display(Name = "Motivo da situação")]
        [StringLength(200)]
        public string MotivoSituacao { get; set; }

        [StringLength(200)]
        public string Tipo { get; set; }

        [StringLength(20)]
        public string Telefone { get; set; }

        public List<Qsa> Qsa { get; set; }

        [Display(Name ="Situação")]
        [StringLength(200)]
        public string Situacao { get; set; }

        [StringLength(25)]
        public string Porte { get; set; }

        [StringLength(20)]
        [Display(Name = "Data de abertura")]
        public string Abertura { get; set; }

        [Display(Name = "Natureza Jurídica")]
        [StringLength(200)]
        public string NaturezaJuridica { get; set; }

        [StringLength(200)]
        public string UltimaAtualizacao { get; set; }

        [StringLength(50)]
        public string Status { get; set; }

        [Display(Name = "Nome fantasia")]
        [StringLength(200)]
        public string Fantasia { get; set; }

        [StringLength(200)]
        public string Logradouro { get; set; }

        [Display(Name = "Número")]
        [StringLength(8)]
        public string Numero { get; set; }

        [StringLength(200)]
        public string Complemento { get; set; }

        [Display(Name = "CEP")]
        [StringLength(15)]
        public string Cep { get; set; }

        [StringLength(200)]
        public string Bairro { get; set; }

        [Display(Name = "Município")]
        [StringLength(100)]
        public string Municipio { get; set; }

        [Display(Name = "UF")]
        [StringLength(5)]
        public string Uf { get; set; }

        [StringLength(70)]
        public string Email { get; set; }

        [Display(Name = "Ente Federativo Responsável")]
        [StringLength(200)]
        public string Efr { get; set; }

        [Display(Name = "Situação especial")]
        [StringLength(200)]
        public string SituacaoEspecial { get; set; }

        [Display(Name = "Data da situação especial")]
        [StringLength(20)]
        public string DataSituacaoEspecial { get; set; }

        [Display(Name = "Valor do capital social")]
        [StringLength(25)]
        public string CapitalSocial { get; set; }

        [JsonProperty("atividade_principal")]
        [Display(Name = "Atividade principal")]
        [StringLength(200)]
        public List<Atividade> AtividadePrincipal { get; set; }

        [JsonProperty("atividades_secundarias")]
        [Display(Name = "Atividades secundárias")]
        [StringLength(200)]
        public List<AtividadeS> AtividadesSecundarias { get; set; }
    }
}

UpperToolsProject/Controllers/EmpresasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using UpperToolsProject.Data;
using UpperToolsProject.Models;
using UpperToolsProject.Tools.RemovePontuacao;
using UpperToolsProject.Tools.ValidaCnpj;

namespace UpperToolsProject.Controllers
{
    public class EmpresasController : Controller
    {
        private readonly MyDbContext _context;

        public EmpresasController(MyDbContext context)
        {
            _context = context;
        }

        // GET: Empresas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Empresa.ToListAsync());
        }

        // ESTE MÉTODO FAZ COM QUE UMA PÁGINA MOSTRE APENAS OS SÓCIOS DO CNPJ RECEBIDO
        // POST: Empresas/DSocios
        [HttpPost]
        public async Task<IActionResult> Dsocios(Empresa emp)
        {
            var qsatolist = await _context.Qsa.ToListAsync();

            List<Qsa> qsa = new List<Qsa>();

            // SE O CNPJ ENVIADO PELA PÁGINA 'Details' FOR IGUAL À CNPJ's DO BANCO DE DADOS 'Qsa', ENTÃO ESSES CNPJS SÃO ADICIONADOS À UMA LISTA
            foreach (var item in qsatolist)
            {
                if (emp.Cnpj == item.EmpresaCnpj)
                {               
                    qsa.Add(item);
                }
            }
            ViewBag.qsa = qsa;

            // VALIDAÇÃO PARA NOTIFICAR ERRO CASO A EMPRESA NÃO TENHA SÓCIOS
            if (qsa == null || qsa.Count == 0)
            {

             var empresa = await _context.Empresa
                    .FirstOrDefaultAsync(m => m.Cnpj == emp.Cnpj);

                ViewBag.emp = empresa;
                ViewBag.msg = "Este CNPJ não possui sócios";

                return View("Details", empresa);
            }
            return View(qsa);
        }


        // POST: Empresas/AtividadePrimaria
        [HttpPost]
        public async Task<IActionResult> AtividadePrimaria(Empresa emp)
        {
            var ativpr = await _context.Atividade.ToListAsync();

            List<Atividade> atvp = new List<Atividade>();

            // SE O CNPJ ENVIADO PELA PÁGINA 'Details' FOR IGUAL À CNPJ's DO BANCO DE DADOS 'Atividade', ENTÃO ESSES CNPJS SÃO ADICIONADOS À UMA LISTA
            foreach (var item in ativpr)
            {
                if (emp.Cnpj == item.EmpresaCnpj)
                {

                    atvp.Add(item);
                }
            }
         
            ViewBag.nome = "Principal";

            return View("Atividade",atvp);
        }

        // POST: Empresas/AtividadeSecundaria
        [HttpPost]
        public async Task<IActionResult> AtividadeSecundaria(Empresa emp)
        {
            var ativse = await _context.AtividadeS.ToListAsync();

            List<AtividadeS> atvs = new List<AtividadeS>();

            // SE O CNPJ ENVIADO PELA PÁGINA 'Details' FOR IGUAL À CNPJ's DO BANCO DE DADOS 'AtividadeS', ENTÃO ESSES CNPJS SÃO ADICIONADOS À UMA LISTA
            foreach (var item in ativse)
            {
                if (emp.Cnpj == item.EmpresaCnpj)
                {

                    atvs.Add(item);
                }
            }

            ViewBag.nome = "Secundárias";

            return View("AtividadeS", atvs);
        }

        // GET: Empresas/AdicionarCadastro
        public IActionResult AdicionarCadastro()
        {
            return View();
        }

        // ESTE MÉTODO RECEBE UM CNPJ E BUSCA INFORMAÇÕES DA EMPRESA E Á ADICIONA AO BANCO DE DADOS
        // POST: Empresas/AdicionarCadastro
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AdicionarCadastro([Bind("Cnpj")] Empresa empresa)
        {
            HttpClient client = new HttpClient { BaseAddress = new Uri("https://www.receitaws.com.br/v1/cnpj/") };

            string cnpj = empresa.Cnpj;
            cnpj = RemovePontuacao.RmPontCnpj(cnpj); // REMOVE MASCARA/PONTUAÇÕES DO CNPJ RECEBIDO
            var response = await client.GetAsync(cnpj);
            var content = await response.Content.ReadAsStringAsync();

            //CASO HAJA MAIS DE 3 REQUISIÇÕES DE CNPJ EM 1 MINUTO, FEITA PARA A API DA RECEITA FEDERAL, ELA RETORNA STATUS DE ERROR,
            //NESTE CASO, A APLICAÇÃO NOTIFICA QUE O USUÁRIO DEVE ESPERAR UM MOMENTO ATÉ A PROXIMA REQUISIÇÃO
            if (!response.IsSuccessStatusCode)
            {
                TempData["msg"] = "Espere um momento para adicionar um novo CNPJ";
                return RedirectToAction("AdicionarCadastro");
            }
            
            // DESERIALIZA O ARQUIVO JSON RECEBIDO PELA API
            Empresa empresas = JsonConvert.DeserializeObject<Empresa>(content, new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore });


            // VALIDAÇÕES DE CNPJ RECEBIDO
            if (response.IsSuccessStatusCode && empresas.Status == "OK" && ValidaCNPJ.IsCnpj(cnpj))
                {
                    empresas.Cnpj = RemovePontuacao.RmPontCnpj(empresas.Cnpj);
                    if (EmpresaExists(empresas.Cnpj))
                    {
                        TempData["msg"] = "Este cadastro já existe no sistema";
                    }
                    else
                    {
                        _context.Add(empresas);
                        await _context.SaveChangesAsync();
                        TempData["msgSuccess"] = "Cadastro realizado com sucesso!";
                    }
                }       
            else
            {
                TempData["msg"] = "O CNPJ informado é inválido!";
            }
            return RedirectToAction("AdicionarCadastro");
        }

        // GET: Empresas/BuscarCadastro
        public IActionResult BuscarCadastro()
        {
            return View();
        }

        // GET: Empresas/Details
        public IActionResult Details ()
        {
            return View();
        }

        // ESTE MÉTODO APÓS RECEBER UM CNPJ, BUSCA TODAS AS INFORMAÇÕES DA EMPRESA CORRESPONDENTE NO BANCO DE DADOS
        // POST: Empresas/Details/cnpj
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Details(Empresa emp)
        {
            emp.Cnpj = RemovePontuacao.RmPontCnpj(emp.Cnpj);
            string id = emp.Cnpj;
            string nome = emp.Nome;

            if (id == null && nome == null)
            {
                TempData["msg"] = "O CNPJ informado é inválido!";
                return RedirectToAction("BuscarCadastro");
            }

            Empresa empresa = null;
            if (id != null)
            {
                empresa = await _context.Empresa
                    .FirstOrDefaultAsync(m => m.Cnpj == id);
            }

            if (nome != null)
            {
                empresa = await _context.Empresa
                    .FirstOrDefaultAsync(m => m.Nome == nome);
            }

            if (empresa == null)
            {
                TempData["msg"] = "O dado informado não está no banco de dados!";
                return RedirectToAction("BuscarCadastro");
            }
            ViewBag.emp = empresa;

            return View(empresa);
        }

        // GET: Empresas/Delete/
        public IActionResult Delete()
        {
            return View();
        }

        // ESTE METODO RECEBE UM CNPJ E DELETA TODAS AS INFORMAÇÕES DA EMPRESA CORRESPONDENTE
        // POST: Empresas/Delete/cnpj
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Empresa emp)
        {
            string id = emp.Cnpj;

            id = RemovePontuacao.RmPontCnpj(id);
            var empresa = await _context.Empresa.FindAsync(id);

            var qsatolist = await _context.Qsa.ToListAsync();
            var atptolist = await _context.Atividade.ToListAsync();
            var atstolist = await _context.AtividadeS.ToListAsync();

            foreach (var item in qsatolist)
            {
                if (id == item.EmpresaCnpj)
                _context.Qsa.Remove(item);

            }
            foreach (var item in atptolist)
            {
                if (id == item.EmpresaCnpj)
                    _context.Atividade.Remove(item);

            }
            foreach (var item in atstolist)
            {
                if (id == item.EmpresaCnpj)
                    _context.AtividadeS.Remove(item);

            }


            if (empresa == null)
            {
                TempData["msg"] = "Este CNPJ não está cadastrado";
                return RedirectToAction("Delete");
            }
            
            _context.Empresa.Remove(empresa);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmpresaExists(string id)
        {
            return _context.Empresa.Any(e => e.Cnpj == id);
        }
    }
}

UpperToolsProject/Views/Empresas/AdicionarCadastro.cshtml
@model UpperToolsProject.Models.Empresa

@{
    ViewData["Title"] = "AdicionarCadastro";
}

<h1>Empresas</h1>

<h4>Cadastrar CNPJ</h4>
<hr />

@if (TempData["msgSuccess"] != null)
{
    <p class="alert alert-success" id="successMessage">@TempData["msgSuccess"]</p>
}
@if (TempData["msg"] != null)
{
    <p class="alert alert-danger" id="dangerMessage">@TempData["msg"]</p>
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="AdicionarCadastro">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Cnpj" class="control-label"></label>
                <input placeholder="Digite o CNPJ da empresa" asp-for="Cnpj" class="form-control" />
                <span asp-validation-for="Cnpj" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-outline-dark " >Enviar</button>
            </div>
        </form>
    </div>
</div>
<br />

<div>
    <a asp-action="Index">Voltar</a>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

UpperToolsProject/Views/Empresas/Atividade.cshtml
@model IEnumerable<UpperToolsProject.Models.Atividade>

@{
    ViewData["Title"] = "Details - Atividades";
}

<h1>Informações</h1>

<h4>Atividade @ViewBag.nome</h4>
<hr />

<table class="col-sm table-bordered table-striped ">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.EmpresaCnpj)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Text)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.EmpresaCnpj)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Text)
                </td>
            </tr>

        }
    </tbody>
</table>
<form asp-action="Details" asp-controller="Empresas">
    <input type="hidden" name="Cnpj" value="@(Model.First().EmpresaCnpj)" />
    <input class="btn btn-outline-info" type="submit" value="Voltar" />
</form>

UpperToolsProject/Views/Empresas/AtividadeS.cshtml
@model IEnumerable<UpperToolsProject.Models.AtividadeS>

@{
    ViewData["Title"] = "Details - Atividades";
}

<h1>Informações</h1>

<h4>Atividades @ViewBag.nome</h4>
<hr />

<table class="col-sm table-bordered table-striped ">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.EmpresaCnpj)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Text)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.EmpresaCnpj)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Text)
                </td>
            </tr>

        }
    </tbody>
</table>
<form asp-action="Details" asp-controller="Empresas">
    <input type="hidden" name="Cnpj" value="@(Model.First().EmpresaCnpj)" />
    <input class="btn btn-outline-info" type="submit" value="Voltar" />
</form>

UpperToolsProject/Views/Empresas/BuscarCadastro.cshtml
@model UpperToolsProject.Models.Empresa

@{
    ViewData["Title"] = "BuscarCadastro";
}

<h1>Empresas</h1>

<h4>Buscar</h4>
<hr />

@if (TempData["msg"] != null)
{
    <p class="alert alert-danger" id="dangerMessage">@TempData["msg"]</p>
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Details">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Cnpj" class="control-label" for="cnpj"></label>
                <input asp-for="Cnpj" class="form-control" id="cnpj" />
                <span asp-validation-for="Cnpj" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-sm-4 btn-outline-dark" id="toastrSuccess">Buscar</button>
            </div>
        </form>
    </div>
</div>


<div class="row mt-5">
    <div class="col-md-4">
        <form asp-action="Details">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label" for="nome"></label>
                <input asp-for="Nome" class="form-control" id="nome" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group md-3">
                <input type="submit" value="Buscar" class="btn btn-outline-dark" />
            </div>
        </form>
    </div>
</div>
<br />

<div>
    <a asp-action="Index">Voltar</a>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

UpperToolsProject/Views/Empresas/DSocios.cshtml
@model IEnumerable<UpperToolsProject.Models.Qsa>

@{
    ViewData["Title"] = "Details - Socios";
}

<h1>Informações</h1>
<div>
    <table class="col-sm table-bordered table-striped ">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.EmpresaCnpj)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Nome)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Qual)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {

                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.EmpresaCnpj)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Qual)
                    </td>
                </tr>

            }
        </tbody>
    </table>
</div>
<form asp-action="Details" asp-controller="Empresas">
    <input type="hidden" name="Cnpj" value="@(Model.First().EmpresaCnpj)" />
    <input class="btn btn-outline-info" type="submit" value="Voltar" />
</form>

UpperToolsProject/Views/Empresas/Details.cshtml
@model UpperToolsProject.Models.Empresa

@{
    ViewData["Title"] = "Details";
}

<h1>Informações</h1>

<div>
    <h4>Empresa</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cnpj)
        </dt>
        <dd class="col-sm-10">
            @ViewBag.emp.Cnpj
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DataSituacao)
        </dt>
        <dd class="col-sm-10">
            @ViewBag.emp.DataSituacao
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MotivoSituacao)
        </dt>
        <dd class="col-lg-10">
            @ViewBag.emp.MotivoSituacao
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>
        <dd class="col-sm-10">
            @ViewBag.emp.Tipo
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @ViewBag.emp.Nome
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>
        <dd class="col-sm-10">
            @ViewBag.emp.Telefone
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Situacao)
        </dt>
        <dd class="col-sm-10">
            @ViewBag.emp.Situacao
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Porte)
        </dt>
        <dd class="col-sm-10">
            @ViewBag.emp.Porte
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Abertura)
        </dt>
        <dd class="col-sm-10">
            @ViewBag.emp.Abertura
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NaturezaJuridica)
        </dt>
        <dd class="col-sm-10">
            @ViewBag.emp.NaturezaJuridica
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UltimaAtualizacao)
        </dt>
        <dd class="col-sm-10">
            @ViewBag.emp.UltimaAtualizacao
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class="col-sm-10">
            @ViewBag.emp.Status
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Fantasia)
        </dt>
        <dd class="col-sm-10">
            @ViewBag.emp.Fantasia
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Logradouro)
        </dt>
        <dd class="col-sm-10">
            @ViewBag.emp.Logradouro
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Numero)
        </dt>
        <dd class="col-sm-10">
            @ViewBag.emp.Numero
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Complemento)
        </dt>
        <dd class="col-sm-10">
            @ViewBag.emp.Complemento
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cep)
        </dt>
        <dd class="col-sm-10">
            @ViewBag.emp.Cep
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Bairro)
        </dt>
        <dd class="col-sm-10">
            @ViewBag.emp.Bairro
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Municipio)
        </dt>
        <dd class="col-sm-10">
            @ViewBag.emp.Municipio
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Uf)
        </dt>
        <dd class="col-sm-10">
            @ViewBag.emp.Uf
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @ViewBag.emp.Email
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Efr)
        </dt>
        <dd class="col-sm-10">
            @ViewBag.emp.Efr
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SituacaoEspecial)
        </dt>
        <dd class="col-sm-10">
            @ViewBag.emp.SituacaoEspecial
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DataSituacaoEspecial)
        </dt>
        <dd class="col-sm-10">
            @ViewBag.emp.DataSituacaoEspecial
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CapitalSocial)
        </dt>
        <dd class="col-sm-10">
            @ViewBag.emp.CapitalSocial
        </dd>

    </dl>

    @if (ViewBag.msg != null)
    {
        <p class="alert alert-danger" id="dangerMessage">@ViewBag.msg</p>
    }
    <form asp-action="Dsocios" asp-controller="Empresas">
        <input type="hidden" name="Cnpj" value="@Model.Cnpj" />
        <input class="btn-outline-info" type="submit" value="Sócios" />
    </form>
    <form asp-action="AtividadePrimaria" asp-controller="Empresas">
        <input type="hidden" name="Cnpj" value="@Model.Cnpj" />
        <input class="btn-outline-info" type="submit" value="Atividades Primarias" />
    </form>
    <form asp-action="AtividadeSecundaria" asp-controller="Empresas">
        <input type="hidden" name="Cnpj" value="@Model.Cnpj" />
        <input class="btn-outline-info" type="submit" value="Atividades Secundárias" />
    </form>
</div>
<br/>
<div>
    <a asp-action="BuscarCadastro">Voltar</a>
</div>